### ISSUE TITLE
Add docker-compose example

### ISSUE THREAD

**Issue by jandahl** [tykling/dns_exporter#104]
```
name: dns_exporter
services:
    dns_exporter:
        ports:
            - 15353:15353
        image: tykling/dns_exporter:latest
```
