### ISSUE TITLE
Multiple query_types

### ISSUE THREAD

**Issue by christianhuth** [tykling/dns_exporter#156]
I would like to define a target (e.g. christianhuth.de) and get DNS records of type a, aaaa, mx, ns, ... with one scrape_config.

```yaml
  - job_name: "christianhuth_all_records"
    scrape_interval: "10s"
    metrics_path: "/query"
    params:
      query_type:
        - a
        - aaaa
        - mx
        - ns
        - srv
        - txt
    static_configs:
      - targets:
          - "christianhuth.de"
```

Is there a way to define multiple query_type at once?

**Comment by tykling** [comment]
If you use the target as query_type you can, with `relabel_configs`:

```yaml
  - job_name: "christianhuth_all_records"
    scrape_interval: "10s"
    metrics_path: "/query"
    params:
      query_name: "christianhuth.de"
      server: 9.9.9.9
    static_configs:
      - targets:
        - a
        - aaaa
        - mx
        - ns
        - srv
        - txt
    relabel_configs:
      - source_labels: ["__address__"]
        target_label: "__param_query_type"
      - source_labels: ["__address__"]
        target_label: "instance"
      - target_label: "__address__"
        replacement: "127.0.0.1:15353"
      - target_label: "monitor"
        replacement: "127.0.0.1:15353"
```

Multiple names AND multiple types in the same scrape job is tricky. It is technically possible, but not pretty. It involves passing a list of strings as target which can be split in relabel_configs, so you would have:

```yaml
    static_configs:
      - targets:
        - a|christianhuth.de
        - mx|christianhuth.de
        - a|example.com
        - mx|example.com
```

And then split on | in `relabel_configs`. 

`relabel_configs` play a big role in making multi-target exporters work. They are super flexible but I always have to spend some time (re-)wrapping my head around them. https://relabeler.promlabs.com/ is nice.
